### ISSUE TITLE
wrtc version 0.0.29 dependency

### ISSUE THREAD

**Issue by Neograph734** [rtc-io/rtc-plugin-node#2]
Is this package specifically depending on wrtc 0.0.29? As of now version 0.0.46 is available, which is 5 months newer. Isn't it better to us that instead?

**Comment by DamonOehlman** [comment]
I've proceeded with an update and everything works as expected, the only downside of using 0.0.46 instead of 0.0.29 is that there are no precompiled binaries for that version yet (at least for linux, maybe there is for mac).

This does seem to affect builds on travis at this stage, but I'm sure that is something that I can work out.  The tests do pass locally though.  Feel free to take a look at the current master branch, and let me know if the current version works for you.

**Comment by Neograph734** [comment]
I'll have a look. Thanks!

**Comment by DamonOehlman** [comment]
As per #3 - this has been updated to work with `wrtc@0.0.55` (though I am seeing the tests fail with a segfault so I'll need to investigate that).
